apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Chart.Name }}-app
  labels:
    app: {{ .Chart.Name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Chart.Name }}
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}
    spec:
      initContainers:
        - name: create-config-dir
          image: busybox
          securityContext:
            runAsUser: {{ include "service.value" (dict "context" . "prop" "uid") | int }}
            runAsGroup: {{ include "service.value" (dict "context" . "prop" "gid") | int }}
          command: ['sh', '-c', 'mkdir -p /configRoot/{{ .Chart.Name }} && chmod 700 /configRoot/{{ .Chart.Name }}']
          volumeMounts:
            - name: config-root
              mountPath: /configRoot
      containers:
        - name: {{ .Chart.Name }}
          image: lscr.io/linuxserver/sabnzbd:latest
          env:
            - name: PUID
              value: "{{ include "service.value" (dict "context" . "prop" "uid") | int }}"
            - name: PGID
              value: "{{ include "service.value" (dict "context" . "prop" "gid") | int }}"
            - name: TZ
              value: {{ include "service.value" (dict "context" . "prop" "tz") | quote }}
          ports:
            {{- range (index .Values .Chart.Name).ports }}
            - containerPort: {{ .port }}
              protocol: {{ default "TCP" .protocol }}
            {{- end }}
          volumeMounts:
            - name: config-root
              mountPath: /config
              subPath: {{ .Chart.Name }}
            {{- include "media.volumeMounts" (dict "mediaPaths" .Values.paths.mediaPaths "mediaTypes" (index .Values .Chart.Name "mediaTypes")) | nindent 12 }}
            {{- include "service.volumeMounts" . | nindent 12 }}
      volumes:
        - name: config-root
          hostPath:
            path: {{ required "A value for paths.configRoot is required" .Values.paths.configRoot }}
        {{- include "media.volumes" (dict "mediaPaths" .Values.paths.mediaPaths "mediaTypes" (index .Values .Chart.Name "mediaTypes" )) | nindent 8 }}
        {{- include "service.volumes" . | nindent 8 }}