{{- $app := index .Values .Chart.Name }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: calibre-app
  labels:
    app: calibre
spec:
  replicas: 1
  selector:
    matchLabels:
      app: calibre
  template:
    metadata:
      labels:
        app: calibre
    spec:
      containers:
        - name: calibre
          image: "{{ $app.image.repository }}:{{ $app.image.tag }}"
          imagePullPolicy: {{ $app.image.pullPolicy | default "IfNotPresent" }}
          env:
            - name: PUID
              value: {{ required "A value for calibre.puid is required" .Values.calibre.puid | quote }}
            - name: PGID
              value: {{ required "A value for lidcalibrearr.guid is required" .Values.calibre.guid | quote }}
            - name: TZ
              value: {{ required "A value for tz is required" .Values.tz | quote }}
          ports:
            {{- range .Values.calibre.ports }}
            - containerPort: {{ .port }}
              protocol: {{ default "TCP" .protocol }}
            {{- end }}
          volumeMounts:
            - name: config
              mountPath: /config
            {{- include "media.volumeMounts" (dict "mediaPaths" .Values.paths.mediaPaths "mediaTypes" .Values.calibre.mediaTypes) | nindent 12 }}
      volumes:
        - name: config
          hostPath:
            path: {{ required "A value for paths.configRoot is required" .Values.paths.configRoot }}/calibre
        {{- include "media.volumes" (dict "mediaPaths" .Values.paths.mediaPaths "mediaTypes" .Values.calibre.mediaTypes) | nindent 8 }}