apiVersion: apps/v1
kind: Deployment
metadata:
  name: transmission-app
  labels:
    app: transmission
spec:
  replicas: 1
  selector:
    matchLabels:
      app: transmission
  template:
    metadata:
      labels:
        app: transmission
    spec:
      containers:
        - name: transmission
          image: lscr.io/linuxserver/transmission:latest
          env:
            - name: PUID
              value: {{ required "A value for transmission.puid is required" .Values.transmission.puid | quote }}
            - name: PGID
              value: {{ required "A value for transmission.guid is required" .Values.transmission.guid | quote }}
            - name: TZ
              value: {{ required "A value for tz is required" .Values.tz | quote }}
            - name: TRANSMISSION_WEB_HOME
              value: {{ .Values.transmission.webHome | quote }}
            - name: USER
              value: {{ required "A value for transmission.user is required" .Values.transmission.user | quote }}
            - name: PASS
              value: {{ required "A value for transmission.password is required" .Values.transmission.password | quote }}
          ports:
            {{- range .Values.transmission.ports }}
            - containerPort: {{ .port }}
              protocol: {{ default "TCP" .protocol }}
            {{- end }}
          volumeMounts:
            - name: config
              mountPath: /config
            {{- include "utils.volumeMounts" (dict "mediaPaths" .Values.paths.mediaPaths "mediaTypes" .Values.transmission.mediaTypes) | nindent 12 }}
            - name: downloads
              mountPath: /watch
              subPath: watch
      volumes:
        - name: config
          hostPath:
            path: {{ required "A value for paths.configRoot is required" .Values.paths.configRoot }}/transmission
        {{- include "utils.volumes" (dict "mediaPaths" .Values.paths.mediaPaths "mediaTypes" .Values.transmission.mediaTypes) | nindent 8 }}
