readarr:
  image:
    repository: lscr.io/linuxserver/readarr
    tag: 0.4.17-develop@sha256:f3978bd06611493011137d82ebdd5e49b3ebb17ad921dbd05017d40b7f2000e3
    pullPolicy: IfNotPresent
  ports:
    - name: http
      port: 8787
      targetPort: 8787