readarr:
  image:
    repository: lscr.io/linuxserver/readarr
    tag: 0.4.15-develop@sha256:dddf53728feff451dd96a52b6b7987561453e5fb5a4436512582b74480555c9b
    pullPolicy: IfNotPresent
  ports:
    - name: http
      port: 8787
      targetPort: 8787