readarr:
  image:
    repository: lscr.io/linuxserver/readarr
    tag: 0.4.18-develop@sha256:b6a7420770adeea5cac1f3ee5da606183d014e3f96fb473f3abd88ed11d9f344
    pullPolicy: IfNotPresent
  ports:
    - name: http
      port: 8787
      targetPort: 8787