readarr:
  image:
    repository: lscr.io/linuxserver/readarr
    tag: 0.4.18-develop@sha256:baf471a7101b58f361ef960de91cd15f23bae82d0126df6a9edbeaf5c5aa4392
    pullPolicy: IfNotPresent
  ports:
    - name: http
      port: 8787
      targetPort: 8787