readarr:
  image:
    repository: lscr.io/linuxserver/readarr
    tag: 0.4.16-develop@sha256:607e49b5d2314569164d22549cdb7ba821a33e25d2de323f44c6e3e294273bf0
    pullPolicy: IfNotPresent
  ports:
    - name: http
      port: 8787
      targetPort: 8787