readarr:
  image:
    repository: lscr.io/linuxserver/readarr
    tag: 0.4.17-develop@sha256:d71c575745ab4579ae0dbb4f91244cf9a74d7085d28a927218146466f8e6418c
    pullPolicy: IfNotPresent
  ports:
    - name: http
      port: 8787
      targetPort: 8787