readarr:
  image:
    repository: lscr.io/linuxserver/readarr
    tag: 0.4.15-develop@sha256:0cd1d5073121cc9c3edd208e705b70b438f423f012645dc8b2a7fc9d066f4700
    pullPolicy: IfNotPresent
  ports:
    - name: http
      port: 8787
      targetPort: 8787