transmission:
  ports:
    - name: http
      port: 9091
      targetPort: 9091
    - name: torrent-tcp
      port: 51413
      targetPort: 51413
    - name: torrent-udp
      port: 51413
      targetPort: 51413
      protocol: UDP