{{- $app := index .Values .Chart.Name }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: calibreweb-app
  labels:
    app: calibreweb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: calibreweb
  template:
    metadata:
      labels:
        app: calibreweb
    spec:
      containers:
        - name: calibreweb
          image: "{{ $app.image.repository }}:{{ $app.image.tag }}"
          imagePullPolicy: {{ $app.image.pullPolicy | default "IfNotPresent" }}
          env:
            - name: PUID
              value: {{ required "A value for calibreweb.puid is required" .Values.calibreweb.puid | quote }}
            - name: PGID
              value: {{ required "A value for calibreweb.guid is required" .Values.calibreweb.guid | quote }}
            - name: TZ
              value: {{ required "A value for tz is required" .Values.tz | quote }}
          ports:
            {{- range .Values.calibreweb.ports }}
            - containerPort: {{ .port }}
              protocol: {{ default "TCP" .protocol }}
            {{- end }}
          volumeMounts:
            - name: config
              mountPath: /config
            {{- include "media.volumeMounts" (dict "mediaPaths" .Values.paths.mediaPaths "mediaTypes" .Values.calibreweb.mediaTypes) | nindent 12 }}
      volumes:
        - name: config
          hostPath:
            path: {{ required "A value for paths.configRoot is required" .Values.paths.configRoot }}/calibreweb
        {{- include "media.volumes" (dict "mediaPaths" .Values.paths.mediaPaths "mediaTypes" .Values.calibreweb.mediaTypes) | nindent 8 }}