apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: calibreweb-ingress
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-cloudflare"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/proxy-body-size: {{ required "A value for calibreweb.uploadSize is required" .Values.calibreweb.uploadSize }}
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - calibreweb.{{ required "A value for domain is required" .Values.domain }}
      secretName: calibreweb-tls-secret
  rules:
    - host: calibreweb.{{ required "A value for domain is required" .Values.domain }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: calibreweb-service
                port:
                  number: {{ include "utils.portByName" (dict "ports" .Values.calibreweb.ports "portName" "http") }}