apiVersion: v2
name: kube-prometheus-stack
description: A Helm chart for installing kube-prometheus-stack
type: application
version: 0.1.0
appVersion: 0.1.0

dependencies:
  - name: utils
    version: 0.1.0
    repository: "file://../../common/utils"
  - name: kube-prometheus-stack
    version: "71.1.0"
    repository: "https://prometheus-community.github.io/helm-charts/"