grafana:
  ports:
    - name: http
      port: 80
      targetPort: 80
prometheus:
  ports:
    - name: http
      port: 9090
      targetPort: 9090
alertmanager:
  ports:
    - name: http
      port: 9093
      targetPort: 9093