apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Chart.Name }}-app
  labels:
    app: {{ .Chart.Name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Chart.Name }}
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}
    spec:
      initContainers:
        - name: create-config-dir
          image: busybox
          securityContext:
            runAsUser: {{ include "service.value" (dict "context" . "prop" "uid") | int }}
            runAsGroup: {{ include "service.value" (dict "context" . "prop" "gid") | int }}
          command: ['sh', '-c', 'mkdir -p /configRoot/{{ .Chart.Name }} && chmod 700 /configRoot/{{ .Chart.Name }}']
          volumeMounts:
            - name: config-root
              mountPath: /configRoot
      containers:
        - name: {{ .Chart.Name }}
          image: lscr.io/linuxserver/prowlarr:latest
          env:
            - name: PUID
              value: "{{ include "service.value" (dict "context" . "prop" "uid") | int }}"
            - name: PGID
              value: "{{ include "service.value" (dict "context" . "prop" "gid") | int }}"
            - name: TZ
              value: {{ include "service.value" (dict "context" . "prop" "tz") | quote }}
          ports:
            {{- range (index .Values .Chart.Name).ports }}
            - containerPort: {{ .port }}
              protocol: {{ default "TCP" .protocol }}
            {{- end }}
          volumeMounts:
            - name: config-root
              mountPath: /config
              subPath: {{ .Chart.Name }}

        {{- if (index .Values .Chart.Name "socks5" "enabled") }}
        - name: socks5-sidecar
          image: alpine:latest
          command:
            - /bin/sh
            - -c
            - |
              apk add --no-cache openssh-client && \
              ssh -o StrictHostKeyChecking=no \
                  -o ServerAliveInterval=60 \
                  -i /ssh-keys/{{ (index .Values .Chart.Name "socks5" "secret-key") }} \
                  -p {{ (index .Values .Chart.Name "socks5" "port") }} \
                  -N -D 0.0.0.0:{{ (index .Values .Chart.Name "socks5" "port") }} \
                  {{ (index .Values .Chart.Name "socks5" "user") }}@{{ (index .Values .Chart.Name "socks5" "host") }};
          ports:
            - containerPort: {{ (index .Values .Chart.Name "socks5" "port") }}
              protocol: TCP
              name: socks5
          volumeMounts:
            - name: ssh-keys
              mountPath: /ssh-keys
              readOnly: true
        {{- end }}
      volumes:
        - name: config-root
          hostPath:
            path: {{ required "A value for paths.configRoot is required" .Values.paths.configRoot }}
        {{- if and (index .Values .Chart.Name "socks5" "enabled") }}
        - name: ssh-keys
          secret:
            secretName: {{ (index .Values .Chart.Name "socks5" "secret") }}
            items:
              - key: (index .Values .Chart.Name "socks5" "secret-key")
                path: (index .Values .Chart.Name "socks5" "secret-key")
        {{- end }}