prowlarr:
  image:
    repository: lscr.io/linuxserver/prowlarr
    tag: 1.35.1@sha256:dec1e580aad36bccaeb1aba283f01a5263761905c304875a603c9a952ecfda79
    pullPolicy: IfNotPresent
  ports:
    - name: http
      port: 9696
      targetPort: 9696
  socks5:
    enabled: false
    user: "myuser"
    host: "host"
    port: 1080
    secret: k8s-secret-name
    secret-key: id_rsa