prowlarr:
  image:
    repository: lscr.io/linuxserver/prowlarr
    tag: 1.35.1@sha256:c63b71155541de52a9e60ba13fd10824a59f649812ca18701509b7b804a5253a
    pullPolicy: IfNotPresent
  ports:
    - name: http
      port: 9696
      targetPort: 9696
  socks5:
    enabled: false
    user: "myuser"
    host: "host"
    port: 1080
    secret: k8s-secret-name
    secret-key: id_rsa