prowlarr:
  image:
    repository: lscr.io/linuxserver/prowlarr
    tag: 1.37.0@sha256:b058be8a4e083e0cba238f03759994617a559abe0c89e5ed66454b44395da6a9
    pullPolicy: IfNotPresent
  ports:
    - name: http
      port: 9696
      targetPort: 9696
  socks5:
    enabled: false
    user: "myuser"
    host: "host"
    port: 1080
    secret: k8s-secret-name
    secret-key: id_rsa