prowlarr:
  image:
    repository: lscr.io/linuxserver/prowlarr
    tag: 1.33.3@sha256:e3242cf552ed1818f9e8208c7826e6b3a28b9203c9732fb0dae176b0323954f2
    pullPolicy: IfNotPresent
  ports:
    - name: http
      port: 9696
      targetPort: 9696
  socks5:
    enabled: false
    user: "myuser"
    host: "host"
    port: 1080
    secret: k8s-secret-name
    secret-key: id_rsa