prowlarr:
  image:
    repository: lscr.io/linuxserver/prowlarr
    tag: 1.35.1@sha256:85718606c75bc0924921cb2df05b0f81c8a691952d44a5bc9f9946254493d1b4
    pullPolicy: IfNotPresent
  ports:
    - name: http
      port: 9696
      targetPort: 9696
  socks5:
    enabled: false
    user: "myuser"
    host: "host"
    port: 1080
    secret: k8s-secret-name
    secret-key: id_rsa