helmfiles:
  - path: helmfiles/infra.yaml
  - path: helmfiles/security.yaml
  - path: helmfiles/media-indexing.yaml
  - path: helmfiles/media-downloading.yaml
  - path: helmfiles/media-management.yaml
  - path: helmfiles/media-streaming.yaml
  - path: helmfiles/tools.yaml
