ip:
uid: 1000
gid: 1000
tz: Europe/Madrid
domain:

# Paths used by the applications
paths:
  configRoot:
  mediaPaths:
    downloads:
    # - name: downloads
    #   path: /mnt/Downloads
    movies:
    # - name: movies1
    #   path: /mnt/Movies1
    #   localize: true
    # - name: movies2
    #   path: /mnt/Movies2
    #   localize: true
    tv-shows:
    # - name: tv-shows
    #   path: /mnt/TvShows
    #   localize: true
    music:
    # - name: music1
    #   path: /mnt/Music
    sports:
    # - name: sports1
    #   path: /mnt/Sports
    books:
    # - name: books1
    #   path: /mnt/Books

# Features to enable
features:
  downloading: true
  indexing: true
  media-management: true
  media-streaming: true
  tools: true
  dev: false
  observability: true

# Infra applications
letsencrypt:
  acme:
    email:

cloudflare:
  email:
  apiToken:

# Services

## Media Downloading applications
transmission:
  enabled: true
  user:
  password:
  webHome: #Optional alternative web interface (needs to be manually installed inside transmission config folder and the value you gat is someting like /config/flood-for-transmission eg: https://github.com/johman10/flood-for-transmission)
  mediaTypes:
    - downloads

sabnzbd:
  enabled: false
  mediaTypes:
    - downloads

## Media Indexing applications
prowlarr:
  enabled: true

nzbhydra2:
  enabled: true

## Media Management applications
radarr:
  enabled: true
  defaultEnabled: true
# languages: # Optional list of languages to create a Radarr instance for each language (radar-es for example)
#   - es
  mediaTypes:
    - movies
    - downloads

sonarr:
  enabled: true
  defaultEnabled: true
# languages: # Optional list of languages to create a Sonarr instance for each language (radar-es for example)
#   - es
  mediaTypes:
    - tv-shows
    - downloads

bazarr:
  enabled: true
  mediaTypes:
    - movies
    - tv-shows

lidarr:
  enabled: true
  mediaTypes:
    - music
    - downloads

readarr:
  enabled: true
  mediaTypes:
    - books
    - downloads

calibre:
  enabled: true
  mediaTypes:
    - books

calibreweb:
  enabled: true
  mediaTypes:
    - books

jellyseerr:
  enabled: true
  defaultEnabled: true
# languages: # Optional list of languages to create a jellyseerr instance for each language (jellyseerr-es for example)
#   - es

overseerr:
  enabled: true
  defaultEnabled: true
# languages: # Optional list of languages to create an overseerr instance for each language (overseerr-es for example)
#   - es

## Media Streaming applications
jellyfin:
  enabled: true
# extraMediaLanguages: # Optional list of language suffixes to mount media volumes
#   - es
  mediaTypes:
    - movies
    - tv-shows
    - sports
    - music
    - downloads

plex:
  enabled: true
  claim: # obtain in https://www.plex.tv/claim/
# extraMediaLanguages: # Optional list of language suffixes to mount media volumes
#   - es
  mediaTypes:
    - movies
    - tv-shows
    - sports
    - music
    - downloads

emby:
  enabled: false
  # extraMediaLanguages: # Optional list of language suffixes to mount media volumes
  #   - es
  mediaTypes:
    - movies
    - tv-shows
    - sports
    - music
    - downloads

xteve:
  enabled: true

threadfin:
  enabled: true

## Tools applications
kubernetes-dashboard:
  enabled: true

homarr:
  enabled: true

homeassistant:
  enabled: true

fileflows:
  enabled: true
  volumes:
    - name: storage
      hostPath:
        path: /storage
  volumeMounts:
    - name: storage
      mountPath: /storage

filebrowser:
  enabled: true
  root: /storage

flaresolverr:
  enabled: true

## Dev applications
renovate:
  enabled: false
  cronjob:
    enabled: true
    schedule: "@daily"
  job:
    enabled: false
  token: # Personal Access Token from github

docker-registry:
  enabled: false
  volumes:
    - name: storage
      hostPath:
        path: /storage
  volumeMounts:
    - name: storage
      mountPath: /storage

## Observability applications
metrics-server:
  enabled: true

kube-prometheus-stack:
  enabled: true
  grafana:
    adminUser: "admin"
    adminPassword: # Password for the admin user