ip:

domain:

paths:
  configRoot:
  mediaPaths:
    downloads:
    # - name: downloads
    #   path: /mnt/Downloads
    movies:
    # - name: movies1
    #   path: /mnt/Movies1
    # - name: movies2
    #   path: /mnt/Movies2
    series:
    # - name: series1
    #   path: /mnt/Series
    music:
    # - name: music1
    #   path: /mnt/Music
    sports:
    # - name: sports1
    #   path: /mnt/Sports

letsencrypt:
  acme:
    email:

cloudflare:
  email:
  apiToken:

wireguard:
  peers: # List of client names

transmission:
  user:
  password:
  webHome: #Optional alternative web interface (needs to be manually installed inside transmission config folder and the value you gat is someting like /config/flood-for-transmission eg: https://github.com/johman10/flood-for-transmission)
  mediaTypes:
    - downloads

radarr:
  mediaTypes:
    - movies
    - downloads

sonarr:
  mediaTypes:
    - series
    - downloads

bazarr:
  mediaTypes:
    - movies
    - series

lidarr:
  mediaTypes:
    - music
    - downloads

jellyfin:
  mediaTypes:
    - movies
    - series
    - sports
    - music
    - downloads