apiVersion: apps/v1
kind: Deployment
metadata:
  name: nzbhydra2-app
  labels:
    app: nzbhydra2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nzbhydra2
  template:
    metadata:
      labels:
        app: nzbhydra2
    spec:
      containers:
        - name: nzbhydra2
          image: lscr.io/linuxserver/nzbhydra2:latest
          env:
            - name: PUID
              value: {{ required "A value for nzbhydra2.puid is required" .Values.nzbhydra2.puid | quote }}
            - name: PGID
              value: {{ required "A value for nzbhydra2.guid is required" .Values.nzbhydra2.guid | quote }}
            - name: TZ
              value: {{ required "A value for tz is required" .Values.tz | quote }}
          ports:
            {{- range .Values.nzbhydra2.ports }}
            - containerPort: {{ .port }}
              protocol: {{ default "TCP" .protocol }}
            {{- end }}
          volumeMounts:
            - name: config
              mountPath: /config
            {{- include "utils.volumeMounts" (dict "mediaPaths" .Values.paths.mediaPaths "mediaTypes" .Values.nzbhydra2.mediaTypes) | nindent 12 }}
      volumes:
        - name: config
          hostPath:
            path: {{ required "A value for paths.configRoot is required" .Values.paths.configRoot }}/nzbhydra2
        {{- include "utils.volumes" (dict "mediaPaths" .Values.paths.mediaPaths "mediaTypes" .Values.nzbhydra2.mediaTypes) | nindent 8 }}