apiVersion: v1
kind: Service
metadata:
  name: nzbhydra2-service
spec:
  type: ClusterIP
  selector:
    app: nzbhydra2
  ports:
    {{- range .Values.nzbhydra2.ports }}
    - name: {{ .name }}
      port: {{ .port }}
      targetPort: {{ .targetPort }}
      protocol: {{ default "TCP" .protocol }}
    {{- end }}