nzbhydra2:
  image:
    repository: lscr.io/linuxserver/nzbhydra2
    tag: 7.15.1@sha256:9082c855f33d4d4407cb1158242fe477334574e4cadc7dfdc7abbc845db817f8
    pullPolicy: IfNotPresent
  ports:
    - name: http
      port: 5076
      targetPort: 5076