nzbhydra2:
  image:
    repository: lscr.io/linuxserver/nzbhydra2
    tag: 7.15.3@sha256:379926a2f5bf6d126ff1a92cf7e6fdeb791aaaf05bbf9b0e4cdf0d0321009f6a
    pullPolicy: IfNotPresent
  ports:
    - name: http
      port: 5076
      targetPort: 5076