nzbhydra2:
  image:
    repository: lscr.io/linuxserver/nzbhydra2
    tag: 7.12.3@sha256:16c019eee364baaa726d248d9234bad586db84191de41bae8858733dc756ae67
    pullPolicy: IfNotPresent
  ports:
    - name: http
      port: 5076
      targetPort: 5076