{{- if .Values.jellyseerr.defaultEnabled }}
  {{- $context := merge (dict "language" nil) (deepCopy .) }}
  {{- include "jellyseerr.deployment" $context | nindent 0 }}
{{- end }}

{{- /* Ensure there's a separation between the defaultEnabled deployment and the language-specific deployments */}}
{{- if and .Values.jellyseerr.defaultEnabled (gt (len .Values.jellyseerr.languages) 0) }}
---
{{- end }}

{{- if and .Values.jellyseerr.languages (gt (len .Values.jellyseerr.languages) 0) }}
  {{/* Capture the original context outside of the range */}}
  {{- $rootContext := . }}
  {{- range $index, $lang := .Values.jellyseerr.languages }}
  {{- if $index }}
---
  {{- end }}
    {{/* Now merge using the captured root context, not the loop item context */}}
    {{- $context := merge (dict "language" $lang) (deepCopy $rootContext) }}
    {{- include "jellyseerr.deployment" $context | nindent 0 }}
  {{- end }}
{{- end }}