apiVersion: apps/v1
kind: Deployment
metadata:
  name: overseerr-app
  labels:
    app: overseerr
spec:
  replicas: 1
  selector:
    matchLabels:
      app: overseerr
  template:
    metadata:
      labels:
        app: overseerr
    spec:
      containers:
        - name: overseerr
          image: lscr.io/linuxserver/overseerr:latest
          env:
            - name: PUID
              value: {{ required "A value for overseerr.puid is required" .Values.overseerr.puid | quote }}
            - name: PGID
              value: {{ required "A value for overseerr.guid is required" .Values.overseerr.guid | quote }}
            - name: TZ
              value: {{ required "A value for tz is required" .Values.tz | quote }}
          ports:
            {{- range .Values.overseerr.ports }}
            - containerPort: {{ .port }}
              protocol: {{ default "TCP" .protocol }}
            {{- end }}
          volumeMounts:
            - name: config
              mountPath: /config
      volumes:
        - name: config
          hostPath:
            path: {{ required "A value for paths.configRoot is required" .Values.paths.configRoot }}/overseerr