apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: overseerr-ingress
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-cloudflare"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - overseerr.{{ required "A value for domain is required" .Values.domain }}
      secretName: overseerr-tls-secret
  rules:
    - host: overseerr.{{ required "A value for domain is required" .Values.domain }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: overseerr-service
                port:
                  number: {{ include "utils.portByName" (dict "ports" .Values.overseerr.ports "portName" "http") }}
