sonarr:
  image:
    repository: lscr.io/linuxserver/sonarr
    tag: 4.0.15@sha256:e3916c86db3c78156d5fcca8d86df5d4ed2ce9c4b476b606a7c4d2ba06a25dde
    pullPolicy: IfNotPresent
  ports:
    - name: http
      port: 8989
      targetPort: 8989