sonarr:
  image:
    repository: lscr.io/linuxserver/sonarr
    tag: 4.0.15@sha256:b0ac15772c04f329964ed79cb446ab23fd1ee28f33b58b10f0264feac17d33cd
    pullPolicy: IfNotPresent
  ports:
    - name: http
      port: 8989
      targetPort: 8989