sonarr:
  image:
    repository: lscr.io/linuxserver/sonarr
    tag: 4.0.15@sha256:1156329d544b38bd1483add75c9b72c559f20e1ca043fd2d6376c2589d38951f
    pullPolicy: IfNotPresent
  ports:
    - name: http
      port: 8989
      targetPort: 8989