sonarr:
  image:
    repository: lscr.io/linuxserver/sonarr
    tag: 4.0.15@sha256:4afcb099e40ef263a7327f1ee9a870a510a516f872ae79b863c11b94d0b9ebb7
    pullPolicy: IfNotPresent
  ports:
    - name: http
      port: 8989
      targetPort: 8989