sonarr:
  image:
    repository: lscr.io/linuxserver/sonarr
    tag: 4.0.14@sha256:5581b2188f11ea6693e0dfe3f3c3198bb605b78088ec685ad579a5a308cc0d5d
    pullPolicy: IfNotPresent
  ports:
    - name: http
      port: 8989
      targetPort: 8989