sonarr:
  image:
    repository: lscr.io/linuxserver/sonarr
    tag: 4.0.14@sha256:de67e5b682fedcc4ac34f28a5697931c680c959ea65f8111b0cce17bc698c0b2
    pullPolicy: IfNotPresent
  ports:
    - name: http
      port: 8989
      targetPort: 8989