sonarr:
  image:
    repository: lscr.io/linuxserver/sonarr
    tag: 4.0.14@sha256:bae1b72ad55cee030a416aaaef1f20eee076e4c1c6d490689904d4609a2cabac
    pullPolicy: IfNotPresent
  ports:
    - name: http
      port: 8989
      targetPort: 8989