sonarr:
  image:
    repository: lscr.io/linuxserver/sonarr
    tag: 4.0.14@sha256:cdf5eb3cfa207d46b066bfbb41b03576c67a1f6ecc8aba19146d0f7349ec79dc
    pullPolicy: IfNotPresent
  ports:
    - name: http
      port: 8989
      targetPort: 8989