sonarr:
  image:
    repository: lscr.io/linuxserver/sonarr
    tag: 4.0.14@sha256:cefa1c97ba8f5db60c1c89d04015ead764d3b850b4fbdc5784bdde2a02d72350
    pullPolicy: IfNotPresent
  ports:
    - name: http
      port: 8989
      targetPort: 8989