apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}-service
spec:
  type: ClusterIP
  selector:
    app: {{ .Chart.Name }}
  ports:
    {{- range (index .Values .Chart.Name).ports }}
    - name: {{ .name }}
      port: {{ .port }}
      targetPort: {{ .targetPort }}
      protocol: {{ default "TCP" .protocol }}
    {{- end }}