filebrowser:
  image:
    repository: filebrowser/filebrowser
    tag: v2.34.2@sha256:0244defba61b8557096cb0d3974b67bd36bbaf1a14e9dd77d1a8f3e3498317e5
    pullPolicy: IfNotPresent
  ports:
    - name: http
      port: 8080
      targetPort: 8080