filebrowser:
  image:
    repository: filebrowser/filebrowser
    tag: v2.36.1@sha256:25a17f9ba8ecbfd26a267e9f35a26b7658792ec34c3d45ed5d1cef4a451a1726
    pullPolicy: IfNotPresent
  ports:
    - name: http
      port: 8080
      targetPort: 8080