filebrowser:
  image:
    repository: filebrowser/filebrowser
    tag: v2.33.2@sha256:57a7a972787ae64ca4d26c2c3cb2cdd05f258e8aca250ade6ea2c206341c03bd
    pullPolicy: IfNotPresent
  ports:
    - name: http
      port: 8080
      targetPort: 8080