filebrowser:
  image:
    repository: filebrowser/filebrowser
    tag: v2.35.0@sha256:bd3f058cb4e88112317c1a6a3e0bc60ec3444fe056707ecd712bcbb1003b71e5
    pullPolicy: IfNotPresent
  ports:
    - name: http
      port: 8080
      targetPort: 8080