filebrowser:
  image:
    repository: filebrowser/filebrowser
    tag: v2.38.0@sha256:1acf323924130eff7ed9ebd0bd7e2250f101ef387b6c77822cc55dfe42417fed
    pullPolicy: IfNotPresent
  ports:
    - name: http
      port: 8080
      targetPort: 8080