filebrowser:
  image:
    repository: filebrowser/filebrowser
    tag: v2.32.0@sha256:593478e3c24c5ea9f5d7478dc549965b7bc7030707291006ce8d0b6162d3454b
    pullPolicy: IfNotPresent
  ports:
    - name: http
      port: 8080
      targetPort: 8080