filebrowser:
  image:
    repository: filebrowser/filebrowser
    tag: v2.34.0@sha256:6b1b9262fca986d2f838e1ea8c7ec35ec41f47f74bdf1cda7f2923a87e59ed5e
    pullPolicy: IfNotPresent
  ports:
    - name: http
      port: 8080
      targetPort: 8080