filebrowser:
  image:
    repository: filebrowser/filebrowser
    tag: v2.33.6@sha256:51bf8322beb9745b9cf803954665258668e16cbef3b6861e4bd03cffbbcc0215
    pullPolicy: IfNotPresent
  ports:
    - name: http
      port: 8080
      targetPort: 8080