filebrowser:
  image:
    repository: filebrowser/filebrowser
    tag: v2.33.8@sha256:b31708528d91e54d5a8f2e1778e8e752966bea787e596eaea191de874fa832ea
    pullPolicy: IfNotPresent
  ports:
    - name: http
      port: 8080
      targetPort: 8080