filebrowser:
  image:
    repository: filebrowser/filebrowser
    tag: v2.36.3@sha256:9f4f394e54d760498cb94def10fe1baa77a95402b7bc42a5d129588e795ed281
    pullPolicy: IfNotPresent
  ports:
    - name: http
      port: 8080
      targetPort: 8080