filebrowser:
  image:
    repository: filebrowser/filebrowser
    tag: v2.33.4@sha256:5e59717cd0216dd7fbf609ec70043540adf4d5ce4a4da3de24bd18e8670fb718
    pullPolicy: IfNotPresent
  ports:
    - name: http
      port: 8080
      targetPort: 8080