filebrowser:
  image:
    repository: filebrowser/filebrowser
    tag: v2.33.0@sha256:766a2a52a769156ee1fd33853213b4ce3d29d724c7af88c94ff8680474fd41d1
    pullPolicy: IfNotPresent
  ports:
    - name: http
      port: 8080
      targetPort: 8080