filebrowser:
  image:
    repository: filebrowser/filebrowser
    tag: v2.33.10@sha256:dd2e1d8f7382d53afab915fea6bb49cd38112587e766a70241b120cd00f517c2
    pullPolicy: IfNotPresent
  ports:
    - name: http
      port: 8080
      targetPort: 8080