filebrowser:
  image:
    repository: filebrowser/filebrowser
    tag: v2.36.0@sha256:2f9c8b964f51d56a4e92583c8a09204722fba90dd66ae28836a2e3f563c7cb71
    pullPolicy: IfNotPresent
  ports:
    - name: http
      port: 8080
      targetPort: 8080