apiVersion: apps/v1
kind: Deployment
metadata:
  name: home-assistant-app
  labels:
    app: home-assistant
spec:
  replicas: 1
  selector:
    matchLabels:
      app: home-assistant
  template:
    metadata:
      labels:
        app: home-assistant
    spec:
      hostNetwork: true
      containers:
        - name: home-assistant
          image: lscr.io/linuxserver/homeassistant:latest
          env:
            - name: PUID
              value: {{ required "A value for homeassistant.puid is required" .Values.homeassistant.puid | quote }}
            - name: PGID
              value: {{ required "A value for homeassistant.guid is required" .Values.homeassistant.guid | quote }}
            - name: TZ
              value: {{ required "A value for tz is required" .Values.tz | quote }}
          ports:
            {{- range .Values.homeassistant.ports }}
            - containerPort: {{ .port }}
              protocol: {{ default "TCP" .protocol }}
            {{- end }}
          volumeMounts:
            - name: config
              mountPath: /config
      volumes:
        - name: config
          hostPath:
            path: {{ required "A value for paths.configRoot is required" .Values.paths.configRoot }}/home-assistant