apiVersion: v1
kind: Service
metadata:
  name: home-assistant-service
spec:
  type: ClusterIP
  selector:
    app: home-assistant
  ports:
    {{- range .Values.homeassistant.ports }}
    - name: {{ .name }}
      port: {{ .port }}
      targetPort: {{ .targetPort }}
      protocol: {{ default "TCP" .protocol }}
    {{- end }}