overseerr:
  image:
    repository: lscr.io/linuxserver/overseerr
    tag: 2021.12.12@sha256:6c3f4115d2ec1fe661de971ac6bc8405a606ac56c5f834d9de290e6df52fe79d
    pullPolicy: IfNotPresent
  ports:
    - name: http
      port: 5056
      targetPort: 5055