qbittorrent:
  image:
    repository: lscr.io/linuxserver/qbittorrent
    tag: 5.1.0@sha256:dc7de5505e7bb806270c9d1ad2f13ad5861dffe02eaff09084624db6f3c1b64e
    pullPolicy: IfNotPresent
  internal-ports:
    - name: http
      port: 8080
      targetPort: 8080
  external-ports:
    - name: torrent-tcp
      port: 31415
      targetPort: 31415
      nodePort: 31415
    - name: torrent-udp
      port: 31415
      targetPort: 31415
      protocol: UDP
      nodePort: 31415