qbittorrent:
  image:
    repository: lscr.io/linuxserver/qbittorrent
    tag: 20.04.1@sha256:fc98c8af048936d0070dc5e5992feab08664f8a61a860d91be02f782f8721485
    pullPolicy: IfNotPresent
  internal-ports:
    - name: http
      port: 8080
      targetPort: 8080
  external-ports:
    - name: torrent-tcp
      port: 31415
      targetPort: 31415
      nodePort: 31415
    - name: torrent-udp
      port: 31415
      targetPort: 31415
      protocol: UDP
      nodePort: 31415