qbittorrent:
  image:
    repository: lscr.io/linuxserver/qbittorrent
    tag: 5.1.1@sha256:1afa9ee70f38adaebb4b2ade4e720d9add5b7d4f0ef4e679f17d94ca002f00bc
    pullPolicy: IfNotPresent
  internal-ports:
    - name: http
      port: 8080
      targetPort: 8080
  external-ports:
    - name: torrent-tcp
      port: 31415
      targetPort: 31415
      nodePort: 31415
    - name: torrent-udp
      port: 31415
      targetPort: 31415
      protocol: UDP
      nodePort: 31415