qbittorrent:
  image:
    repository: lscr.io/linuxserver/qbittorrent
    tag: 5.1.0@sha256:eb16ef40b8ba2b6287184a8961d00c50abb99b3782365df70b63671d5c3504d8
    pullPolicy: IfNotPresent
  internal-ports:
    - name: http
      port: 8080
      targetPort: 8080
  external-ports:
    - name: torrent-tcp
      port: 31415
      targetPort: 31415
      nodePort: 31415
    - name: torrent-udp
      port: 31415
      targetPort: 31415
      protocol: UDP
      nodePort: 31415