qbittorrent:
  image:
    repository: lscr.io/linuxserver/qbittorrent
    tag: 5.1.0@sha256:ca6325989299ff807ab94c9505c138b6cadfe8a77c4ef14c5690094cbbe40d7d
    pullPolicy: IfNotPresent
  internal-ports:
    - name: http
      port: 8080
      targetPort: 8080
  external-ports:
    - name: torrent-tcp
      port: 31415
      targetPort: 31415
      nodePort: 31415
    - name: torrent-udp
      port: 31415
      targetPort: 31415
      protocol: UDP
      nodePort: 31415