deluge:
  image:
    repository: lscr.io/linuxserver/deluge
    tag: 2.2.0@sha256:cf11684c53ff297c94a78f2a576ec7984c1b872e341d494445be301bc08a5f75
    pullPolicy: IfNotPresent
  internal-ports:
    - name: http
      port: 8112
      targetPort: 8112
    - name: thin-client
      port: 58846
      targetPort: 58846
  external-ports:
    - name: torrent-tcp
      port: 31412
      targetPort: 31412
      nodePort: 31412
    - name: torrent-udp
      port: 31412
      targetPort: 31412
      protocol: UDP
      nodePort: 31412