deluge:
  image:
    repository: lscr.io/linuxserver/deluge
    tag: 2.2.0@sha256:31a78a86aaf3b325a6eff875e63f2079b47fe5769d4609dfe574283c0e655c82
    pullPolicy: IfNotPresent
  internal-ports:
    - name: http
      port: 8112
      targetPort: 8112
    - name: thin-client
      port: 58846
      targetPort: 58846
  external-ports:
    - name: torrent-tcp
      port: 31412
      targetPort: 31412
      nodePort: 31412
    - name: torrent-udp
      port: 31412
      targetPort: 31412
      protocol: UDP
      nodePort: 31412