deluge:
  image:
    repository: lscr.io/linuxserver/deluge
    tag: 2.2.0@sha256:2b266d26af73d791797de6be2b761f6417426e71ba1e703423248560d76b2cf0
    pullPolicy: IfNotPresent
  internal-ports:
    - name: http
      port: 8112
      targetPort: 8112
    - name: thin-client
      port: 58846
      targetPort: 58846
  external-ports:
    - name: torrent-tcp
      port: 31412
      targetPort: 31412
      nodePort: 31412
    - name: torrent-udp
      port: 31412
      targetPort: 31412
      protocol: UDP
      nodePort: 31412