docker-registry:
  image:
    repository: registry
    tag: 3.0.0@sha256:1fc7de654f2ac1247f0b67e8a459e273b0993be7d2beda1f3f56fbf1001ed3e7
    pullPolicy: IfNotPresent
  ports:
    - name: http
      port: 5000
      targetPort: 5000