tz: Europe/Madrid
calibreweb:
  image:
    repository: lscr.io/linuxserver/calibre-web
    tag: 0.6.24@sha256:1c16285e36f6b0c3aa06e69f303455ddcdae5651498fff7782d22301db127310
    pullPolicy: IfNotPresent
  puid: 1000
  guid: 1000
  ports:
    - name: http
      port: 8083
      targetPort: 8083
  uploadSize: 128m