calibre:
  image:
    repository: lscr.io/linuxserver/calibre
    tag: 8.5.0@sha256:2ff7fbcc54a352b878751be23f1fe651c61ad7548e7e0d3c7b61d117f663b3fc
    pullPolicy: IfNotPresent
  puid: 1000
  guid: 1000
  ports:
    - name: http
      port: 8080
      targetPort: 8080
    - name: http-api
      port: 8081
      targetPort: 8081