calibre:
  image:
    repository: lscr.io/linuxserver/calibre
    tag: 8.4.0@sha256:2abc022999ff914dd3e23dd7edb70c104918bb324c0b03175ae990cedc5a1d11
    pullPolicy: IfNotPresent
  puid: 1000
  guid: 1000
  ports:
    - name: http
      port: 8080
      targetPort: 8080
    - name: http-api
      port: 8081
      targetPort: 8081