calibre:
  image:
    repository: lscr.io/linuxserver/calibre
    tag: 8.3.0@sha256:1aa40a56c82839f37e379f25f78984be571e3b024614b9eb26ac6b6f12a5db29
    pullPolicy: IfNotPresent
  puid: 1000
  guid: 1000
  ports:
    - name: http
      port: 8080
      targetPort: 8080
    - name: http-api
      port: 8081
      targetPort: 8081