calibre:
  image:
    repository: lscr.io/linuxserver/calibre
    tag: 8.5.0@sha256:5094ffa9c7f8451f940f2c2fdaecf8acb09a89fe2bd87e9266c0bbad7119e326
    pullPolicy: IfNotPresent
  puid: 1000
  guid: 1000
  ports:
    - name: http
      port: 8080
      targetPort: 8080
    - name: http-api
      port: 8081
      targetPort: 8081