calibre:
  image:
    repository: lscr.io/linuxserver/calibre
    tag: 8.6.0@sha256:fb84ff8f639b561a5d68fadfc3ffa259d461273ecb9285f9c0854f596c00e2b1
    pullPolicy: IfNotPresent
  puid: 1000
  guid: 1000
  ports:
    - name: http
      port: 8080
      targetPort: 8080
    - name: http-api
      port: 8081
      targetPort: 8081