calibre:
  image:
    repository: lscr.io/linuxserver/calibre
    tag: 8.3.0@sha256:bf331da647a7ab96dfa33ba1a485da3849c11b3b982e00e6993811aba200161e
    pullPolicy: IfNotPresent
  puid: 1000
  guid: 1000
  ports:
    - name: http
      port: 8080
      targetPort: 8080
    - name: http-api
      port: 8081
      targetPort: 8081