radarr:
  image:
    repository: lscr.io/linuxserver/radarr
    tag: 5.26.2@sha256:3f6c13cd920e60469e24fac6b25338b0805832e6dea108f8316814d0f4147ab6
    pullPolicy: IfNotPresent
  ports:
    - name: http
      port: 7878
      targetPort: 7878