radarr:
  image:
    repository: lscr.io/linuxserver/radarr
    tag: 5.23.3@sha256:532749cc71739130720c9d1cd8b8fbec204f6c8bd94fd633fccb4b566a672a55
    pullPolicy: IfNotPresent
  ports:
    - name: http
      port: 7878
      targetPort: 7878