radarr:
  image:
    repository: lscr.io/linuxserver/radarr
    tag: 5.21.1@sha256:5ad8df1b0dc0bb0c2232a9278b85c3c230d82184415f83238b5969da8dc6a942
    pullPolicy: IfNotPresent
  ports:
    - name: http
      port: 7878
      targetPort: 7878