radarr:
  image:
    repository: lscr.io/linuxserver/radarr
    tag: 5.22.4@sha256:01233b9ea9435fd00eab51891f133d86c9b6293f5adb8c3bf44e7a314c9c3423
    pullPolicy: IfNotPresent
  ports:
    - name: http
      port: 7878
      targetPort: 7878