radarr:
  image:
    repository: lscr.io/linuxserver/radarr
    tag: 5.22.4@sha256:105b7ffb9e88880a55a3fcd6116542f19af21aae8884a4e276e007d2816bbacb
    pullPolicy: IfNotPresent
  ports:
    - name: http
      port: 7878
      targetPort: 7878