radarr:
  image:
    repository: lscr.io/linuxserver/radarr
    tag: 5.21.1@sha256:9a4a7ed79dee5fcc9940b57ddfddfe7c87dea2d13a221ca2fdd2c1c8d9e75c2e
    pullPolicy: IfNotPresent
  ports:
    - name: http
      port: 7878
      targetPort: 7878