radarr:
  image:
    repository: lscr.io/linuxserver/radarr
    tag: 5.24.1@sha256:d51c77a4e8fb4af0776ec032d103a84f816e65d09010fc72025ddd309d4c2424
    pullPolicy: IfNotPresent
  ports:
    - name: http
      port: 7878
      targetPort: 7878