radarr:
  image:
    repository: lscr.io/linuxserver/radarr
    tag: 5.26.2@sha256:07a474b61394553e047ad43a1a78c1047fc99be0144c509dd91e3877f402ebcb
    pullPolicy: IfNotPresent
  ports:
    - name: http
      port: 7878
      targetPort: 7878