radarr:
  image:
    repository: lscr.io/linuxserver/radarr
    tag: 5.25.0@sha256:36e43720c130ec2d3ed80726d2134af3c6644729f4750abc830fdda7fa71d1e1
    pullPolicy: IfNotPresent
  ports:
    - name: http
      port: 7878
      targetPort: 7878