home-assistant:
  image:
    repository: lscr.io/linuxserver/homeassistant
    tag: 2025.5.2@sha256:8f7952ae45aecbd7568a8936e456f612a2449ec06af23bc59726cbae5a0bdce6
    pullPolicy: IfNotPresent
  ports:
    - name: http
      port: 8123
      targetPort: 8123