home-assistant:
  image:
    repository: lscr.io/linuxserver/homeassistant
    tag: 2025.6.1@sha256:051b7762418a5661c099357cf1d62b852be7dca86baf3da973cd911244255e5f
    pullPolicy: IfNotPresent
  ports:
    - name: http
      port: 8123
      targetPort: 8123