apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-api-token-secret
type: Opaque
data:
  api-token: {{ required "A value for cloudflare.apiToken is required" .Values.cloudflare.apiToken | b64enc }}