n8n:
  image:
    repository: docker.n8n.io/n8nio/n8n
    tag: 1.102.1@sha256:a2be2b83220599db7296bfa34c392aea60051942edb52abae64e891fb7718aac
    pullPolicy: IfNotPresent
  ports:
    - name: http
      port: 5678
      targetPort: 5678