n8n:
  image:
    repository: docker.n8n.io/n8nio/n8n
    tag: 1.95.1@sha256:ea6f3a249fbca9e999fcfc21ba7f02a1345ee330014b503782fc08128be1cb4a
    pullPolicy: IfNotPresent
  ports:
    - name: http
      port: 5678
      targetPort: 5678