n8n:
  image:
    repository: docker.n8n.io/n8nio/n8n
    tag: 1.97.0@sha256:e07088dbf3c1f0cdfbe67beff92399746706e6921be54a88119eae1713a4ff50
    pullPolicy: IfNotPresent
  ports:
    - name: http
      port: 5678
      targetPort: 5678