n8n:
  image:
    repository: docker.n8n.io/n8nio/n8n
    tag: 1.96.0@sha256:63b48ed7e877b26b8a7bcd628bcf328ae5fde63b937ede8b996d18c95106b6cb
    pullPolicy: IfNotPresent
  ports:
    - name: http
      port: 5678
      targetPort: 5678