n8n:
  image:
    repository: docker.n8n.io/n8nio/n8n
    tag: 1.94.0@sha256:82ef2eab8eae7a796cca7ce1f6f5443dbf96f9606e7714773aaccf0e920ce803
    pullPolicy: IfNotPresent
  ports:
    - name: http
      port: 5678
      targetPort: 5678