apiVersion: apps/v1
kind: Deployment
metadata:
  name: wireguard-app
  labels:
    app: wireguard
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wireguard
  template:
    metadata:
      labels:
        app: wireguard
    spec:
      containers:
        - name: wireguard
          image: lscr.io/linuxserver/wireguard:v1.0.20210914-ls22
          securityContext:
            capabilities:
              add:
                - NET_ADMIN
              # SYS_MODULE is generally not supported in Kubernetes as it requires more privileged access
          env:
            - name: PUID
              value: {{ required "A value for wireguard.puid is required" .Values.wireguard.puid | quote }}
            - name: PGID
              value: {{ required "A value for wireguard.guid is required" .Values.wireguard.guid | quote }}
            - name: TZ
              value: {{ required "A value for tz is required" .Values.tz }}
            - name: SERVERURL
              value: vpn.{{ required "A value for domain is required" .Values.domain }}
            - name: SERVERPORT
              value: {{ include "utils.portByName" (dict "ports" .Values.wireguard.ports "portName" "wireguard-port") | quote }}
            - name: PEERS
              value: {{ required "A value for wireguard.peers is required" .Values.wireguard.peers | join "," }}
            - name: PEERDNS
              value: {{ required "A value for ip is required" .Values.ip }}
            - name: INTERNAL_SUBNET
              value: "10.13.13.0"
            - name: ALLOWEDIPS
              value: "0.0.0.0/0"
            - name: PERSISTENTKEEPALIVE_PEERS
              value: ""
            - name: LOG_CONFS
              value: "true"
          volumeMounts:
            - name: config
              mountPath: /config
          ports:
            {{- range .Values.wireguard.ports }}
            - containerPort: {{ .port }}
              protocol: {{ default "TCP" .protocol }}
            {{- end }}
      volumes:
        - name: config
          hostPath:
            path: {{ required "A value for paths.configRoot is required" .Values.paths.configRoot }}/wireguard
            type: DirectoryOrCreate