tautulli:
  image:
    repository: lscr.io/linuxserver/tautulli
    tag: 2.15.2@sha256:a9b699b5cdbc3a79c1d05a250daf1f9f9cba76dc8628d6caeffdbc99b42d8625
    pullPolicy: IfNotPresent
  ports:
    - name: http
      port: 8181
      targetPort: 8181