tautulli:
  image:
    repository: lscr.io/linuxserver/tautulli
    tag: 2.15.2@sha256:73540c967731d36692cea9b8e8881c45e2734f47d5eac1ed6e5e1821f4801737
    pullPolicy: IfNotPresent
  ports:
    - name: http
      port: 8181
      targetPort: 8181