tautulli:
  image:
    repository: lscr.io/linuxserver/tautulli
    tag: 2.15.2@sha256:b30bb4d9e014cfa87c705c225afb48bd12d45423a1a448daae4f2e8cd3f366e2
    pullPolicy: IfNotPresent
  ports:
    - name: http
      port: 8181
      targetPort: 8181