homarr:
  image:
    repository: ghcr.io/homarr-labs/homarr
    tag: v1.28.1@sha256:0daf3070bb205252ae3e681bf55b93bf86c47e53968adc7505b4caff0c14febc
    pullPolicy: IfNotPresent
  ports:
    - name: http
      port: 3000
      targetPort: 3000