homarr:
  image:
    repository: ghcr.io/homarr-labs/homarr
    tag: v1.22.0@sha256:fb8cdf0ee9a7adc76ceea29b94a4a36271e91286d972e20085c554dcc32cc983
    pullPolicy: IfNotPresent
  ports:
    - name: http
      port: 3000
      targetPort: 3000