homarr:
  image:
    repository: ghcr.io/homarr-labs/homarr
    tag: v1.21.0@sha256:3d97e5e677be2ae0a6451ad5305ea4d9ff011a0fc88b56a25683cf7b666f2788
    pullPolicy: IfNotPresent
  ports:
    - name: http
      port: 3000
      targetPort: 3000