homarr:
  image:
    repository: ghcr.io/homarr-labs/homarr
    tag: v1.25.0@sha256:568159d99874f307d57301a88468f2b9e1bf637e5ddb64e39aecb14668de2f6d
    pullPolicy: IfNotPresent
  ports:
    - name: http
      port: 3000
      targetPort: 3000