homarr:
  image:
    repository: ghcr.io/homarr-labs/homarr
    tag: v1.19.1@sha256:29b9f113b26e7a9fc4045ca6e39122d82bd852349416a0a38932fbc1dc93d0fc
    pullPolicy: IfNotPresent
  ports:
    - name: http
      port: 3000
      targetPort: 3000