homarr:
  image:
    repository: ghcr.io/homarr-labs/homarr
    tag: v1.23.0@sha256:bc6b4152dce615954221eecdeacfa6514e8836cb6e34298010fbbbbf21546ce2
    pullPolicy: IfNotPresent
  ports:
    - name: http
      port: 3000
      targetPort: 3000