homarr:
  image:
    repository: ghcr.io/homarr-labs/homarr
    tag: v1.26.0@sha256:fff13eaa6ab7775c4092d6e131ef64ceeaab584c21e7573661d004c3a5de12e2
    pullPolicy: IfNotPresent
  ports:
    - name: http
      port: 3000
      targetPort: 3000