homarr:
  image:
    repository: ghcr.io/homarr-labs/homarr
    tag: v1.18.0@sha256:13e450921b9f1366b67efd22fa026e7fb77422690783ed0679eec016258ef6c5
    pullPolicy: IfNotPresent
  ports:
    - name: http
      port: 3000
      targetPort: 3000