homarr:
  image:
    repository: ghcr.io/homarr-labs/homarr
    tag: v1.17.0@sha256:ade909a22aea766ea232ad63f3f199016e7cc2c6079531c7cce10442a0482d09
    pullPolicy: IfNotPresent
  ports:
    - name: http
      port: 3000
      targetPort: 3000