homarr:
  image:
    repository: ghcr.io/homarr-labs/homarr
    tag: v1.18.1@sha256:de1027a4ba5931b82bf86ed0b255c0dd3ad3a20e47aa6cffcc1e98a67343b27a
    pullPolicy: IfNotPresent
  ports:
    - name: http
      port: 3000
      targetPort: 3000