homarr:
  image:
    repository: ghcr.io/homarr-labs/homarr
    tag: v1.28.0@sha256:3c0796f4c22ef0aaf38d916e7480c6c75ac879c67dbc7b24a8a45641600b685b
    pullPolicy: IfNotPresent
  ports:
    - name: http
      port: 3000
      targetPort: 3000