homarr:
  image:
    repository: ghcr.io/homarr-labs/homarr
    tag: v1.27.0@sha256:2b2460e70ac25124a1a78dcb54f9b3f68492aae136fc03453d9fac04291a445a
    pullPolicy: IfNotPresent
  ports:
    - name: http
      port: 3000
      targetPort: 3000