homarr:
  image:
    repository: ghcr.io/homarr-labs/homarr
    tag: v1.16.0@sha256:5ffc90623f29095bc294022ebc892fe0d968332a41c5ad9e1f23decfcabfcc0d
    pullPolicy: IfNotPresent
  ports:
    - name: http
      port: 3000
      targetPort: 3000