homarr:
  image:
    repository: ghcr.io/homarr-labs/homarr
    tag: v1.20.0@sha256:45b8aceeb466de3cf0044d5864e631c16f76db3939dac82f694b6a4b55459f64
    pullPolicy: IfNotPresent
  ports:
    - name: http
      port: 3000
      targetPort: 3000