homarr:
  image:
    repository: ghcr.io/homarr-labs/homarr
    tag: v1.19.0@sha256:e3030ed3465bc1d57052ebaf2cbb3bdc7cb091fe90c021fd10ca80fa929cb6da
    pullPolicy: IfNotPresent
  ports:
    - name: http
      port: 3000
      targetPort: 3000