{{- if .Values.renovate.cronjob.enabled -}}
apiVersion: batch/v1
kind: CronJob
metadata:
  name: renovate
spec:
  schedule: "{{ required "A value for renovate.cronjob.schedule is required" .Values.renovate.cronjob.schedule }}"
  concurrencyPolicy: Forbid
  failedJobsHistoryLimit: 1
  successfulJobsHistoryLimit: 1
  jobTemplate:
    spec:
      ttlSecondsAfterFinished: 60
      {{- include "chartname.jobSpec" . | nindent 6 }}
{{- end -}}