apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: alertmanager-kube-prometheus-ingress
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-cloudflare"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - alertmanager.kube-prometheus.{{ required "A value for domain is required" .Values.domain }}
      secretName: alertmanager-kube-prometheus-tls-secret
  rules:
    - host: alertmanager.kube-prometheus.{{ required "A value for domain is required" .Values.domain }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: kube-prometheus-stack-alertmanager
                port:
                  number: {{ include "utils.portByName" (dict "ports" .Values.alertmanager.ports "portName" "http") }}
