plex:
  image:
    repository: lscr.io/linuxserver/plex
    tag: 1.41.6@sha256:c799512e714ea3c5bf5d4589b56a16e29d56bcf8ecfbfc368245514fe6500171
    pullPolicy: IfNotPresent
  ports:
    - name: http
      port: 32400
      targetPort: 32400
  claim: