plex:
  image:
    repository: lscr.io/linuxserver/plex
    tag: 1.41.8@sha256:14e8d783f2b0ec7e7ca2836d3d7185f5e68c60ba0e4eac77666bee4f0f819043
    pullPolicy: IfNotPresent
  ports:
    - name: http
      port: 32400
      targetPort: 32400
  claim: