plex:
  image:
    repository: lscr.io/linuxserver/plex
    tag: 1.41.6@sha256:53e6a94b2649b3c817757bbdf28d7970bc10e036ec0868b0704f3f51aa612742
    pullPolicy: IfNotPresent
  ports:
    - name: http
      port: 32400
      targetPort: 32400
  claim: