plex:
  image:
    repository: lscr.io/linuxserver/plex
    tag: 1.41.8@sha256:2bae6500e2328fbc48fcc9ec1c0c17d6f95e8d024fcbff5c60d154093f29832d
    pullPolicy: IfNotPresent
  ports:
    - name: http
      port: 32400
      targetPort: 32400
  claim: