plex:
  image:
    repository: lscr.io/linuxserver/plex
    tag: 1.41.7@sha256:87cf58fff5adfebc97871837198b73bcf255b3551432be39697fbdbbdc58c8f8
    pullPolicy: IfNotPresent
  ports:
    - name: http
      port: 32400
      targetPort: 32400
  claim: