{{- $app := index .Values .Chart.Name }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Chart.Name }}-app
  labels:
    app: {{ .Chart.Name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Chart.Name }}
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}
    spec:
      initContainers:
        - name: create-config-dir
          image: busybox
          command: [ 'sh', '-c', 'chown {{ include "service.value" (dict "context" . "prop" "uid") | int }}:{{ include "service.value" (dict "context" . "prop" "gid") | int }} /configRoot && chmod 700 /configRoot' ]
          volumeMounts:
            - name: config-root
              mountPath: /configRoot
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ $app.image.repository }}:{{ $app.image.tag }}"
          imagePullPolicy: {{ $app.image.pullPolicy | default "IfNotPresent" }}
          securityContext:
            runAsUser: {{ include "service.value" (dict "context" . "prop" "uid") | int }}
            runAsGroup: {{ include "service.value" (dict "context" . "prop" "gid") | int }}
          volumeMounts:
            - name: config-root
              mountPath: /etc/docker/registry
            {{- include "service.volumeMounts" . | nindent 12 }}
      volumes:
        - name: config-root
          hostPath:
            type: DirectoryOrCreate
            path: {{ required "A value for paths.configRoot is required" .Values.paths.configRoot }}/{{ .Chart.Name }}
        {{- include "service.volumes" . | nindent 8 }}