bazarr:
  image:
    repository: lscr.io/linuxserver/bazarr
    tag: 1.5.1@sha256:f17f0335c1b61aae73dd2b08477ead4ebc6df03f57badddb42a173e4637ee1ed
    pullPolicy: IfNotPresent
  ports:
    - name: http
      port: 6767
      targetPort: 6767