bazarr:
  image:
    repository: lscr.io/linuxserver/bazarr
    tag: 1.5.2@sha256:a92ba81b9405942d0b5c01e2707ba8fb99ab059dd800d1dc0e8f52f62ddf74dd
    pullPolicy: IfNotPresent
  ports:
    - name: http
      port: 6767
      targetPort: 6767