bazarr:
  image:
    repository: lscr.io/linuxserver/bazarr
    tag: 1.5.2@sha256:b515d79a4f7aa4bbbdfe45376d996a9bae2794faa16aca5a2beab0dba0c0b074
    pullPolicy: IfNotPresent
  ports:
    - name: http
      port: 6767
      targetPort: 6767