bazarr:
  image:
    repository: lscr.io/linuxserver/bazarr
    tag: 1.5.2@sha256:558d6ddf36cd87bac5d4fb2ee8488730c4f65718961ef4ca7073062378aa7641
    pullPolicy: IfNotPresent
  ports:
    - name: http
      port: 6767
      targetPort: 6767