bazarr:
  image:
    repository: lscr.io/linuxserver/bazarr
    tag: 1.5.2@sha256:81d76b6c13a7a9481440402f0fa0ff1dc6027d003447da28eb1ed150e1846af7
    pullPolicy: IfNotPresent
  ports:
    - name: http
      port: 6767
      targetPort: 6767