bazarr:
  image:
    repository: lscr.io/linuxserver/bazarr
    tag: 1.5.1@sha256:d6c430bc4bb48979dd8247816af75e4fbb5999535eef7c9515ba8e5dbc8ac80d
    pullPolicy: IfNotPresent
  ports:
    - name: http
      port: 6767
      targetPort: 6767