bazarr:
  image:
    repository: lscr.io/linuxserver/bazarr
    tag: 1.5.1@sha256:b98bdcac54db7ed05524fb63447b855d7fc419428222b3827b1cc9655f95bf51
    pullPolicy: IfNotPresent
  ports:
    - name: http
      port: 6767
      targetPort: 6767