bazarr:
  image:
    repository: lscr.io/linuxserver/bazarr
    tag: 1.5.1@sha256:2219fa5f4db9b33fa187553177daae80e7baa6b0350a3132395c7bf6b4ded771
    pullPolicy: IfNotPresent
  ports:
    - name: http
      port: 6767
      targetPort: 6767