bazarr:
  image:
    repository: lscr.io/linuxserver/bazarr
    tag: 1.5.2@sha256:a848b8a1d9e3b2553157ceb72cd3fc6ae2b34e71bcece24561b0944fb7922b46
    pullPolicy: IfNotPresent
  ports:
    - name: http
      port: 6767
      targetPort: 6767