bazarr:
  image:
    repository: lscr.io/linuxserver/bazarr
    tag: 1.5.2@sha256:7fa77912d9cc0573ca4efd9ac542aba4fd51eb6d331c3ad7aac7bc7fca48b929
    pullPolicy: IfNotPresent
  ports:
    - name: http
      port: 6767
      targetPort: 6767