bazarr:
  image:
    repository: lscr.io/linuxserver/bazarr
    tag: 1.5.2@sha256:2458b13b6bdb9beee13acd2c70172140e9f9362488914d9f7cd95a473c3742b7
    pullPolicy: IfNotPresent
  ports:
    - name: http
      port: 6767
      targetPort: 6767