{{- if .Values.radarr.defaultEnabled }}
  {{- $context := merge (dict "language" nil) (deepCopy .) }}
  {{- include "radarr.service" $context | nindent 0 }}
{{- end }}

{{- /* Ensure there's a separation between the defaultEnabled service and the language-specific service */}}
{{- if and .Values.radarr.defaultEnabled (gt (len .Values.radarr.languages) 0) }}
---
{{- end }}

{{- if and .Values.radarr.languages (gt (len .Values.radarr.languages) 0) }}
  {{/* Capture the original context outside of the range */}}
  {{- $rootContext := . }}
  {{- range $index, $lang := .Values.radarr.languages }}
  {{- if $index }}
---
  {{- end }}
    {{/* Now merge using the captured root context, not the loop item context */}}
    {{- $context := merge (dict "language" $lang) (deepCopy $rootContext) }}
    {{- include "radarr.service" $context | nindent 0 }}
  {{- end }}
{{- end }}