fileflows:
  image:
    repository: revenz/fileflows
    tag: 25.06@sha256:4b89ae604eb9777ca2f8add5597b1027d67c24f459e290a3dda0d1564ff39b94
    pullPolicy: IfNotPresent
  ports:
    - name: http
      port: 5000
      targetPort: 5000