fileflows:
  image:
    repository: revenz/fileflows
    tag: 25.05@sha256:90263cb2fc002f40a33feba4ee0c70692ef5620b4ab325433de958cdb0b51498
    pullPolicy: IfNotPresent
  ports:
    - name: http
      port: 5000
      targetPort: 5000