fileflows:
  image:
    repository: revenz/fileflows
    tag: 25.05@sha256:c7f94a3f78277fbc1e5e0682064c2e0e0c740161b96a1bce14319b90858442fc
    pullPolicy: IfNotPresent
  ports:
    - name: http
      port: 5000
      targetPort: 5000