fileflows:
  image:
    repository: revenz/fileflows
    tag: 25.04@sha256:d69067584e5f90aa3c96b5cac9dbeb5934e19ec7260f39198010989a73a74a25
    pullPolicy: IfNotPresent
  ports:
    - name: http
      port: 5000
      targetPort: 5000