fileflows:
  image:
    repository: revenz/fileflows
    tag: 25.04@sha256:f26308bbe29c2299680cb7bed008fbe0505aaf8d6e83d97dc0284061ca5bfcf6
    pullPolicy: IfNotPresent
  ports:
    - name: http
      port: 5000
      targetPort: 5000