fileflows:
  image:
    repository: revenz/fileflows
    tag: 25.06@sha256:7d4e5bd0917a8d96609b7c540bdd8acc6e4eae9475fc1a53dc3845333042dbce
    pullPolicy: IfNotPresent
  ports:
    - name: http
      port: 5000
      targetPort: 5000