fileflows:
  image:
    repository: revenz/fileflows
    tag: 25.07@sha256:df5225e1aacc9b535e91cabc5914409ebd676d3848d332e7cae4df858e6fab44
    pullPolicy: IfNotPresent
  ports:
    - name: http
      port: 5000
      targetPort: 5000