fileflows:
  image:
    repository: revenz/fileflows
    tag: 25.04@sha256:842a3b4d22b54b8488bb0c2365ef17767233d32cd92e00459e51dce2c4702fa8
    pullPolicy: IfNotPresent
  ports:
    - name: http
      port: 5000
      targetPort: 5000