fileflows:
  image:
    repository: revenz/fileflows
    tag: 25.06@sha256:6dd85a56fe0caa89e063ee278a3a2b8ee9ed861023320c9dc53f4292480debc1
    pullPolicy: IfNotPresent
  ports:
    - name: http
      port: 5000
      targetPort: 5000