fileflows:
  image:
    repository: revenz/fileflows
    tag: 25.06@sha256:2564e618aae62904e346668efe799af50a2c1ca79cfd542c2e0c906226f186e3
    pullPolicy: IfNotPresent
  ports:
    - name: http
      port: 5000
      targetPort: 5000