fileflows:
  image:
    repository: revenz/fileflows
    tag: 25.04@sha256:3a10d5a1b3ace88a9b9c7439bb03271dd12b2f9e098c9d5bc311333a675da0ec
    pullPolicy: IfNotPresent
  ports:
    - name: http
      port: 5000
      targetPort: 5000