fileflows:
  image:
    repository: revenz/fileflows
    tag: 25.05@sha256:bcf18525514c7e60c425fbbd715ac2c778e97c1d166a4f5ab3091705a1d3be4e
    pullPolicy: IfNotPresent
  ports:
    - name: http
      port: 5000
      targetPort: 5000