sabnzbd:
  image:
    repository: lscr.io/linuxserver/sabnzbd
    tag: 4.5.1@sha256:913d57a64e9c9039c758b8f80e13226c3e226f7ffec34fbc56702421ace4c48c
    pullPolicy: IfNotPresent
  ports:
    - name: http
      port: 8080
      targetPort: 8080