sabnzbd:
  image:
    repository: lscr.io/linuxserver/sabnzbd
    tag: 4.5.2@sha256:88d9dcb1eb1615b3980d37824b5e40a7df60af49a268d97aeccbe5f7107edf92
    pullPolicy: IfNotPresent
  ports:
    - name: http
      port: 8080
      targetPort: 8080