sabnzbd:
  image:
    repository: lscr.io/linuxserver/sabnzbd
    tag: 4.5.1@sha256:ff713ec0a51f8831f3d95c4e2298763a699e26dc3b4806876d886969f08a46a8
    pullPolicy: IfNotPresent
  ports:
    - name: http
      port: 8080
      targetPort: 8080