sabnzbd:
  image:
    repository: lscr.io/linuxserver/sabnzbd
    tag: 4.5.1@sha256:64fef49beb0bf1df043c556c2abf1b8485031fad6409995d75ee93e201359d52
    pullPolicy: IfNotPresent
  ports:
    - name: http
      port: 8080
      targetPort: 8080