sabnzbd:
  image:
    repository: lscr.io/linuxserver/sabnzbd
    tag: 4.5.1@sha256:5a46efd411bd4c6d12706defe483ad1d34e36f758b44a15ae0be662f02c58194
    pullPolicy: IfNotPresent
  ports:
    - name: http
      port: 8080
      targetPort: 8080