sabnzbd:
  image:
    repository: lscr.io/linuxserver/sabnzbd
    tag: 4.5.1@sha256:8d4575787eedeb36d7857cffb441dffc8c0e0e2d32be6fc08ec6a9749ec94322
    pullPolicy: IfNotPresent
  ports:
    - name: http
      port: 8080
      targetPort: 8080