sabnzbd:
  image:
    repository: lscr.io/linuxserver/sabnzbd
    tag: 4.5.1@sha256:219f9d2508849a916614840e48bc0d09769724a0bd2cb031d42572cdefc23c04
    pullPolicy: IfNotPresent
  ports:
    - name: http
      port: 8080
      targetPort: 8080