sabnzbd:
  image:
    repository: lscr.io/linuxserver/sabnzbd
    tag: 4.5.1@sha256:47f4b5d4eb7d2fa34e5bf1ab78ac8173d8fa355ceeafb11aa0c3847e3b366105
    pullPolicy: IfNotPresent
  ports:
    - name: http
      port: 8080
      targetPort: 8080