sabnzbd:
  image:
    repository: lscr.io/linuxserver/sabnzbd
    tag: 4.5.1@sha256:4087a051fa3aec7c320db624f572eba71513bcb34b146fbd036b8c7c92b78bfa
    pullPolicy: IfNotPresent
  ports:
    - name: http
      port: 8080
      targetPort: 8080