sabnzbd:
  image:
    repository: lscr.io/linuxserver/sabnzbd
    tag: 4.5.1@sha256:15d7fb05cb46efdb0572ffb2b3b1f6962d8b5f1cf3bb8304f39493ea81fcf066
    pullPolicy: IfNotPresent
  ports:
    - name: http
      port: 8080
      targetPort: 8080