sabnzbd:
  image:
    repository: lscr.io/linuxserver/sabnzbd
    tag: 4.5.1@sha256:dc87d24f47257c738394cd2d82b547c0482b0b5e5824f483d42a8699ad5793de
    pullPolicy: IfNotPresent
  ports:
    - name: http
      port: 8080
      targetPort: 8080