apiVersion: v1
kind: ConfigMap
metadata:
  name: custom-dns
data:
  Corefile: |
    .:53 {
      errors
      health
      ready
      forward . 8.8.8.8 8.8.4.4
      cache 30
    }
    {{ required "A value for domain is required" .Values.domain }}:53 {
      errors
      cache 30
      template ANY ANY {
        match ^(.*)\.lupionandrade\.com\.$
        answer "{{`{{ .Name }}`}} 60 IN A {{ required "A value for ip is required" .Values.ip }}"
      }
      forward . 8.8.8.8 8.8.4.4
      header {
        response set ra
      }
    }
