apiVersion: apps/v1
kind: Deployment
metadata:
  name: custom-dns-app
  labels:
      app: custom-dns
spec:
  replicas: 1
  selector:
    matchLabels:
      app: custom-dns
  template:
    metadata:
      labels:
        app: custom-dns
    spec:
      containers:
        - name: coredns
          image: "coredns/coredns:1.11.1"
          args: [ "-conf", "/etc/coredns/Corefile" ]
          volumeMounts:
            - name: config-volume
              mountPath: /etc/coredns
              readOnly: true
          ports:
            - containerPort: 53
              protocol: UDP
      volumes:
        - name: config-volume
          configMap:
            name: custom-dns
