apiVersion: v2
name: xteve
description: A Helm chart for setting up xteve
type: application
version: 0.1.0
appVersion: 0.1.0

dependencies:
  - name: utils
    version: 0.1.0
    repository: "file://../../common/utils"