flaresolverr:
  image:
    repository: flaresolverr/flaresolverr
    tag: v3.3.25@sha256:68160ec125e5cde23bc45549a443da0da0223cf4f0de7571ed2c6851cf6e1561
    pullPolicy: IfNotPresent
  ports:
    - name: http
      port: 8191
      targetPort: 8191