flaresolverr:
  image:
    repository: flaresolverr/flaresolverr
    tag: v3.3.22@sha256:4cfcff3e93f86eab2131e263322f2ef0d25fc362d450f67acfb6bcda687748e9
    pullPolicy: IfNotPresent
  ports:
    - name: http
      port: 8191
      targetPort: 8191