apiVersion: v1
kind: Secret
metadata:
  name: {{ .Chart.Name }}-password-secret
type: Opaque
data:
  password: {{ required "A value for password is required" (index .Values .Chart.Name "password") | b64enc | quote }}