jellyfin:
  image:
    repository: lscr.io/linuxserver/jellyfin
    tag: 10.10.7@sha256:58cf629c955968b94157e6607797bd285ad4d408d83ca2ea4bfc7dffbc2c3661
    pullPolicy: IfNotPresent
  ports:
    - name: http
      port: 8096
      targetPort: 8096
    - name: discovery-1
      port: 7359
      targetPort: 7359
      protocol: UDP
    - name: discovery-2
      port: 1900
      targetPort: 1900
      protocol: UDP