jellyfin:
  image:
    repository: lscr.io/linuxserver/jellyfin
    tag: 10.10.7@sha256:3c967e55bed1b36332629e1896e9f2ef82e176bd19f495838deef4e4bbdaed05
    pullPolicy: IfNotPresent
  ports:
    - name: http
      port: 8096
      targetPort: 8096
    - name: discovery-1
      port: 7359
      targetPort: 7359
      protocol: UDP
    - name: discovery-2
      port: 1900
      targetPort: 1900
      protocol: UDP