transmission:
  image:
    repository: lscr.io/linuxserver/transmission
    tag: 4.0.6@sha256:5b0565989e039155492765f69894c918de0388271a97bf83ded1bf63552a8bcd
    pullPolicy: IfNotPresent
  internal-ports:
    - name: http
      port: 9091
      targetPort: 9091
  external-ports:
    - name: torrent-tcp
      port: 31413
      targetPort: 31413
      nodePort: 31413
    - name: torrent-udp
      port: 31413
      targetPort: 31413
      protocol: UDP
      nodePort: 31413