transmission:
  image:
    repository: lscr.io/linuxserver/transmission
    tag: 4.0.6@sha256:a4d7d6f283649e8a7d0279130d59a3e16d9c6ba19cf5cd53faac3024dc1122dd
    pullPolicy: IfNotPresent
  internal-ports:
    - name: http
      port: 9091
      targetPort: 9091
  external-ports:
    - name: torrent-tcp
      port: 31413
      targetPort: 31413
      nodePort: 31413
    - name: torrent-udp
      port: 31413
      targetPort: 31413
      protocol: UDP
      nodePort: 31413