apiVersion: v1
kind: Service
metadata:
  name: filebrowser-service
spec:
  type: ClusterIP
  selector:
    app: filebrowser
  ports:
    {{- range .Values.filebrowser.ports }}
    - name: {{ .name }}
      port: {{ .port }}
      targetPort: {{ .targetPort }}
      protocol: {{ default "TCP" .protocol }}
    {{- end }}