jellyseerr:
  image:
    repository: fallenbagel/jellyseerr
    tag: 2.5.2@sha256:2a611369ad1d0d501c2d051fc89b6246ff081fb4a30879fdc75642cf6a37b1a6
    pullPolicy: IfNotPresent
  ports:
    - name: http
      port: 5055
      targetPort: 5055