jellyseerr:
  image:
    repository: fallenbagel/jellyseerr
    tag: 2.7.0@sha256:3ec2ce92445719ea1e610b3e758da20cd317c8e1028fc810d001b1370a339226
    pullPolicy: IfNotPresent
  ports:
    - name: http
      port: 5055
      targetPort: 5055