jellyseerr:
  image:
    repository: fallenbagel/jellyseerr
    tag: 2.6.0@sha256:8f320036d937d84c385ea5800f87d69ba16ec4d3770fccf6cad803b5e8d66a52
    pullPolicy: IfNotPresent
  ports:
    - name: http
      port: 5055
      targetPort: 5055