lidarr:
  image:
    repository: lscr.io/linuxserver/lidarr
    tag: 2.10.3@sha256:a6a7991f217f3c8b2bfffce1eb962e84b7ecd3cf7869f1456af54d0551bac9b7
    pullPolicy: IfNotPresent
  ports:
    - name: http
      port: 8686
      targetPort: 8686