lidarr:
  image:
    repository: lscr.io/linuxserver/lidarr
    tag: 2.11.2@sha256:d44312a0849e84970a5f13db183eda993861078e5b9d1fdec31a0daa53226a24
    pullPolicy: IfNotPresent
  ports:
    - name: http
      port: 8686
      targetPort: 8686