lidarr:
  image:
    repository: lscr.io/linuxserver/lidarr
    tag: 2.11.2@sha256:273641e57caa284a1439b062eea2faed965761d6b7bda78a687184080a901cc2
    pullPolicy: IfNotPresent
  ports:
    - name: http
      port: 8686
      targetPort: 8686