lidarr:
  image:
    repository: lscr.io/linuxserver/lidarr
    tag: 2.11.2@sha256:e01a6968d2c58f04278a67da9690e62b0cba07f5dbacb03b0cfbf195940f94a7
    pullPolicy: IfNotPresent
  ports:
    - name: http
      port: 8686
      targetPort: 8686