lidarr:
  image:
    repository: lscr.io/linuxserver/lidarr
    tag: 2.11.2@sha256:eca135d4c2bfd0472c56002bd865d87822d9d439a2ba7e72a2615c0382db85bc
    pullPolicy: IfNotPresent
  ports:
    - name: http
      port: 8686
      targetPort: 8686