lidarr:
  image:
    repository: lscr.io/linuxserver/lidarr
    tag: 2.10.3@sha256:df4309a9325d4a404c0494d67a3d80fec9ba09eb83ae2eb013d98d1cbfcd5751
    pullPolicy: IfNotPresent
  ports:
    - name: http
      port: 8686
      targetPort: 8686