lidarr:
  image:
    repository: lscr.io/linuxserver/lidarr
    tag: 2.12.4@sha256:71fe6d5702691c6ac8961b9b1042fdea1ff833a49c82c5e165346fa88999a48a
    pullPolicy: IfNotPresent
  ports:
    - name: http
      port: 8686
      targetPort: 8686