lidarr:
  image:
    repository: lscr.io/linuxserver/lidarr
    tag: 2.12.4@sha256:b1daebbda8ee180e509bb726378b0dd7816ac29eef43a8e85f6071be4d4e6904
    pullPolicy: IfNotPresent
  ports:
    - name: http
      port: 8686
      targetPort: 8686