lidarr:
  image:
    repository: lscr.io/linuxserver/lidarr
    tag: 2.11.2@sha256:3a7d5f70fec9f694eedfef7241a5cf6e2723bf280f1320d8f6b7fba44b14032e
    pullPolicy: IfNotPresent
  ports:
    - name: http
      port: 8686
      targetPort: 8686