lidarr:
  image:
    repository: lscr.io/linuxserver/lidarr
    tag: 8.1.2135@sha256:8455e2c2f3a7e0fb56ab4de6be924d81aa441bfe9a740cf110d46b25a39b42ba
    pullPolicy: IfNotPresent
  ports:
    - name: http
      port: 8686
      targetPort: 8686